mist_token = ''
org_id = ''
SLACK_TOKEN = ''
mist_sites = "/api/v1/orgs/"+ org_id +"/sites"
#mist_api = "https://api.mist.com"
mist_api = "https://api.gc1.mist.com"
#mist_api = "https://api.gc2.mist.com"
#mist_api = "https://api.ac2.mist.com"
#mist_api = "https://api.eu.mist.com"
psk_ssid = ''
home_site = ''